### ISSUE TITLE
Need a way to set cpu limits for non-throttled startup

### ISSUE THREAD

**Issue by AlexanderBrevig** [entur/helm-charts#1]
Maybe either add
```
common:
  container:
    cpu: 0.1
    cpuLimit: 0.5  # suggested API
```
or make sure we can use `mulf` (multiply floats) and set limit based on a factor (i.e 5x) of `cpu`
