### ISSUE TITLE
Use internalPort to specify k8s' grpc probe ports

### ISSUE THREAD

**Issue by elgbar** [entur/helm-charts#101]
Currently you have set all ports manually, even if they should be the same as `common.service.internalPort` so one have to write something like this:

```yaml
common:
  grpc: true
  service:
    internalPort: &grpc_port 8091
  container:
    probes:
      liveness:
        grpc:
          port: *grpc_port
      readiness:
        grpc:
          port: *grpc_port
      startup:
        grpc:
          port: *grpc_port
```

It would be niceer to be shorten the config down to enabling the use of the new internal probes with a toggle, like so:

```yaml
common:
  grpc: true
  service:
    internalPort: &grpc_port 8091
  container:
    probes:
      use_k8s_grpc: true # Explicitly enable internal probes here
```
