### ISSUE TITLE
same name, or option to set custom name, for k8s secrets using secret option

### ISSUE THREAD

**Issue by Chr1stian** [entur/helm-charts#129]
From the example:

```
app: my-app-with-secrets
shortname: myapps
team: platform
env: dev

ingress:
  trafficType: api
  host: test.dev.entur.io

container:
  name: my-app
  image: theimage

secrets: # enables external-secrets
  secret-manager-secrets:  # name of k8s secret to be mounted
    - SECRET_ONE  # name of secret in secret manager
```

This generates the k8s secret with name `my-app-with-secrets-secret-manager-secrets` instead of just the expected `secret-manager-secrets`
