### ISSUE TITLE
Set custom HPA behavior

### ISSUE THREAD

**Issue by Chr1stian** [entur/helm-charts#39]
Allow users to set their own values for HPA. E.g
```
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 2
          periodSeconds: 15
```

https://bitbucket.org/enturas/offers/src/master/helm/offers/templates/horizontalAutoScaler.yaml
