### ISSUE TITLE
Set `deployment.maxReplicas` for charts that uses `containers` and not `container`

### ISSUE THREAD

**Issue by AlexanderBrevig** [entur/helm-charts#82]
This should work:

```yaml
common:
  deployment:
    maxReplicas: 5
```
